# Generated by Django 6.0.3 on 2026-04-22 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_alter_group_description_alter_group_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Lista de Exercícios',
                'verbose_name_plural': 'Listas de Exercícios',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('code', 'Código'), ('complete_code', 'Completar Código'), ('multiple_choice', 'Múltipla Escolha')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('statement', models.TextField(verbose_name='Enunciado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='activity.activitylist', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompleteCodeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++')], max_length=20, verbose_name='Linguagem')),
                ('starter_code', models.TextField(verbose_name='Código Incompleto')),
                ('complete_code', models.TextField(verbose_name='Código Completo (Gabarito)')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complete_code_exercise', to='activity.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='CodeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++')], max_length=20, verbose_name='Linguagem')),
                ('starter_code', models.TextField(blank=True, verbose_name='Código Inicial')),
                ('expected_output', models.TextField(verbose_name='Output Esperado')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_exercise', to='activity.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_exercise', to='activity.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto da Opção')),
                ('is_correct', models.BooleanField(default=False, verbose_name='É Correta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='activity.multiplechoiceexercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityListGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Vinculado em')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('activity_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_groups', to='activity.activitylist')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_list_groups', to='group.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('activity_list', 'group'), name='unique_activitylist_group')],
            },
        ),
    ]
