# Generated by Django 6.0.3 on 2026-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylist',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicada'),
        ),
    ]
