# Generated by Django 6.0.3 on 2026-04-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitylist_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='description',
            field=models.TextField(blank=True, help_text='Descreva o objetivo da atividade, os tópicos abordados e quaisquer instruções importantes para os alunos.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='title',
            field=models.CharField(help_text='Dê um título claro e descritivo para a atividade, que reflita seu conteúdo e objetivo principal.', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='statement',
            field=models.TextField(help_text='Descreva o enunciado do exercício de forma clara e detalhada.', verbose_name='Enunciado'),
        ),
    ]
