# Generated by Django 6.0.3 on 2026-04-23 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_exercise_title_alter_activitylist_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseoption',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='exerciseoption',
            name='order',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='statement',
            field=models.TextField(help_text='Descreva o enunciado do exercício de forma clara e detalhada.', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('code', 'Código'), ('complete_code', 'Completar Código'), ('multiple_choice', 'Múltipla Escolha')], help_text='Selecione o tipo de exercício para definir a estrutura e os campos necessários para a criação.', max_length=20, verbose_name='Tipo do Exercício'),
        ),
    ]
