# Generated by Django 6.0.3 on 2026-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_exerciseoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('discursive', 'Discursiva'), ('code', 'Código'), ('complete_code', 'Completar Código'), ('multiple_choice', 'Múltipla Escolha')], help_text='Selecione o tipo de exercício para definir a estrutura e os campos necessários para a criação.', max_length=20, verbose_name='Tipo do Exercício'),
        ),
    ]
