# Generated by Django 6.0.3 on 2026-05-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_exercise_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeexercise',
            name='starter_code',
        ),
        migrations.AlterField(
            model_name='codeexercise',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++')], help_text='Selecione a linguagem de programação para o exercício.', max_length=20, verbose_name='Linguagem'),
        ),
        migrations.AlterField(
            model_name='completecodeexercise',
            name='complete_code',
            field=models.TextField(help_text='Forneça o código completo que serve como gabarito para correção.', verbose_name='Código Completo (Gabarito)'),
        ),
        migrations.AlterField(
            model_name='completecodeexercise',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++')], help_text='Selecione a linguagem de programação para o exercício.', max_length=20, verbose_name='Linguagem'),
        ),
        migrations.AlterField(
            model_name='completecodeexercise',
            name='starter_code',
            field=models.TextField(help_text='Forneça o código inicial com lacunas para o aluno completar. Use "___" para indicar as lacunas.', verbose_name='Código Incompleto'),
        ),
    ]
