# Generated by Django 6.0.3 on 2026-05-20 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_remove_codeexercise_starter_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeexercise',
            name='expected_output',
            field=models.TextField(help_text='Forneça a saída esperada para o exercício.', validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Output Esperado'),
        ),
        migrations.CreateModel(
            name='DiscursiveExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_words', models.PositiveIntegerField(default=50, help_text='Número mínimo de palavras que a resposta deve conter.', verbose_name='Mínimo de Palavras')),
                ('max_words', models.PositiveIntegerField(blank=True, help_text='Número máximo de palavras que a resposta pode conter (opcional).', null=True, verbose_name='Máximo de Palavras')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discursive_exercise', to='activity.exercise')),
            ],
            options={
                'verbose_name': 'Exercício Discursivo',
                'verbose_name_plural': 'Exercícios Discursivos',
            },
        ),
    ]
