# Generated by Django 6.0.3 on 2026-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_codeexercise_expected_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discursiveexercise',
            name='min_words',
            field=models.PositiveIntegerField(default=10, help_text='Número mínimo de palavras que a resposta deve conter.', verbose_name='Mínimo de Palavras'),
        ),
    ]
