# Generated by Django 6.0.3 on 2026-06-20 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_activityarchived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylistgroup',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Informe quanto este exercício vale na composição da atividade.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nota'),
        ),
    ]
