# Generated by Django 6.0.3 on 2026-07-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_activitylistgroup_starts_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeexercise',
            name='expected_output',
        ),
        migrations.CreateModel(
            name='CodeTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, default='', help_text='Valores de entrada para o programa (pode ser vazio se não houver entrada).', verbose_name='Entrada')),
                ('expected_output', models.TextField(help_text='Saída que o programa deve produzir para esta entrada.', verbose_name='Saída esperada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='activity.codeexercise', verbose_name='Exercício')),
            ],
            options={
                'verbose_name': 'Caso de Teste',
                'verbose_name_plural': 'Casos de Teste',
                'ordering': ['order', 'id'],
            },
        ),
    ]
