# Generated by Django 6.0.3 on 2026-07-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_add_code_test_case_remove_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_annulled',
            field=models.BooleanField(default=False, verbose_name='Anulada'),
        ),
    ]
