# Generated by Django 6.0.3 on 2026-07-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_add_exercise_is_annulled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecodeexercise',
            name='starter_code',
            field=models.TextField(help_text='Forneça o código inicial com lacunas. Cada lacuna deve ser marcada com exatamente três underlines: "___". Ex: x = ___', verbose_name='Código Incompleto'),
        ),
    ]
