# Generated by Django 6.0.3 on 2026-07-09 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_set_default_max_attempts_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de tentativas que cada aluno pode realizar. Deixe em branco para tentativas ilimitadas.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Tentativas'),
        ),
    ]
