# Generated by Django 6.0.3 on 2026-07-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_codeexercise_max_executions'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylist',
            name='manual_grading',
            field=models.BooleanField(default=False, help_text='Se marcado, a correção de todos os exercícios fica a cargo do professor. A autocorreção automática no envio é desativada.', verbose_name='Correção manual'),
        ),
    ]
