# Generated by Django 6.0.3 on 2026-04-09 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('shift', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], max_length=10, verbose_name='Turno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='GroupArchived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(db_index=True, default=True, verbose_name='Arquivado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Arquivado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_groups', to='group.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Compartilhado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Está Ativo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='group.group')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado por')),
                ('shared_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_group', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com')),
            ],
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'created_by'), name='unique_group_name_created_by'),
        ),
        migrations.AddConstraint(
            model_name='grouparchived',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_archived_user'),
        ),
        migrations.AddConstraint(
            model_name='groupsharing',
            constraint=models.UniqueConstraint(fields=('group', 'shared_with'), name='unique_group_sharing_with'),
        ),
    ]
