# Generated by Django 6.0.3 on 2026-04-22 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Descreva objetivos, metodologia e informações importantes.', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Digite um nome para identificar esta turma', max_length=100, verbose_name='Nome da Turma'),
        ),
        migrations.AlterField(
            model_name='group',
            name='shift',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], help_text='Horário principal da turma', max_length=10, verbose_name='Turno'),
        ),
    ]
