# Generated by Django 6.0.3 on 2026-04-05 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsharing',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='groupsharing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group', 'shared_with'), name='unique_active_sharing'),
        ),
    ]
