# Generated by Django 6.0.3 on 2026-04-05 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_groupsharing_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupsharing',
            name='unique_active_sharing',
        ),
        migrations.AddConstraint(
            model_name='groupsharing',
            constraint=models.UniqueConstraint(fields=('group', 'shared_with'), name='unique_group_sharing_with'),
        ),
    ]
