# Generated by Django 6.0.3 on 2026-04-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_groupsharing_unique_active_sharing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
