# Generated by Django 6.0.3 on 2026-04-08 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_is_archived_groupsharing_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='groupsharing',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='groupsharing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='groupsharing',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='groupsharing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Compartilhado em'),
        ),
        migrations.CreateModel(
            name='GroupArchived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Arquivado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_groups', to='group.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='unique_group_archived_user')],
            },
        ),
    ]
