# Generated by Django 6.0.3 on 2026-04-08 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_remove_group_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouparchived',
            name='is_archived',
            field=models.BooleanField(default=True, verbose_name='Arquivado'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_group_name_created_by'),
        ),
    ]
