# Generated by Django 6.0.3 on 2026-04-08 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_remove_group_unique_group_name_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está Ativo'),
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='groupsharing',
            name='shared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado por'),
        ),
        migrations.AlterField(
            model_name='groupsharing',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_group', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_group_name_created_by'),
        ),
    ]
