"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('WEB_SECRET_KEY', 'django-insecure-nf8=set_ENV')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv('WEB_DEBUG') == 'true')

ALLOWED_HOSTS = os.getenv('WEB_ALLOWED_HOSTS').split(',')

CSRF_TRUSTED_ORIGINS = os.getenv('WEB_CSRF_TRUSTED_ORIGINS').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'django_select2',

    # Local apps
    'accounts',
    'activity',
    'common',
    'dataset',
    'group',
    'student',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Local apps
    'accounts.middleware.CookieMiddleware', 

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'base_templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'lms'),
        'USER': os.getenv('POSTGRES_USER', 'lms_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'lms_password'),
        'HOST': os.getenv('POSTGRES_CONTAINER_NAME', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Cache Configuration
# https://docs.djangoproject.com/en/6.0/topics/cache/#redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://:{os.getenv('REDIS_PASSWORD', 'redis_password')}@{os.getenv('REDIS_CONTAINER_NAME', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/2",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,
        }
    }
}

CACHES.update({
    'select2': CACHES['default']
})

# Tell select2 which cache configuration to use:
SELECT2_CACHE_BACKEND = "select2"

# Session Configuration
# cached_db: grava no Redis (rápido) + PostgreSQL (fallback). Resiliente a
# falhas do Redis e ao IGNORE_EXCEPTIONS do cache.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/sistemadegestaodeaprendizagem/static/"

STATICFILES_DIRS = [
    BASE_DIR / "base_static",
]

STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/sistemadegestaodeaprendizagem/media/"
MEDIA_ROOT = BASE_DIR / "media"

FORCE_SCRIPT_NAME = "/sistemadegestaodeaprendizagem"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"


# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
_REDIS_HOST = os.getenv('REDIS_CONTAINER_NAME', 'localhost')
_REDIS_PORT = os.getenv('REDIS_PORT', '6379')
_REDIS_PASS = os.getenv('REDIS_PASSWORD', 'redis_password')
_REDIS_BASE  = f'redis://:{_REDIS_PASS}@{_REDIS_HOST}:{_REDIS_PORT}'

CELERY_BROKER_URL       = _REDIS_BASE + '/1'
CELERY_RESULT_BACKEND   = _REDIS_BASE + '/3'
CELERY_RESULT_EXPIRES   = 3600          # 1 hora
CELERY_TASK_SERIALIZER  = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT   = ['json']
CELERY_TIMEZONE         = 'America/Sao_Paulo'
