# Generated by Django 6.0.3 on 2026-06-20 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0012_alter_activitylistgroup_starts_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submetido em')),
                ('activity_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activity.activitylistgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
            },
        ),
        migrations.CreateModel(
            name='ExerciseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name='Resposta')),
                ('is_correct', models.BooleanField(null=True, verbose_name='Correta')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Respondido em')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='activity.exercise')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.exerciseoption', verbose_name='Opção selecionada')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='student.submission')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('student', 'activity_link'), name='unique_student_activity_submission'),
        ),
        migrations.AddConstraint(
            model_name='exerciseanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'exercise'), name='unique_submission_exercise_answer'),
        ),
    ]
