# Generated by Django 6.0.3 on 2026-06-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseanswer',
            name='student_observation',
            field=models.TextField(blank=True, default='', verbose_name='Observação do aluno'),
        ),
        migrations.AddField(
            model_name='exerciseanswer',
            name='teacher_comment',
            field=models.TextField(blank=True, default='', verbose_name='Comentário do professor'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_feedback',
            field=models.TextField(blank=True, default='', verbose_name='Feedback do aluno'),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, default='', verbose_name='Comentário do professor'),
        ),
    ]
