# Generated by Django 6.0.3 on 2026-07-09 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_add_max_attempts_to_activitylist'),
        ('student', '0002_submission_feedback_answer_observations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-attempt_number'], 'verbose_name': 'Submissão', 'verbose_name_plural': 'Submissões'},
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_student_activity_submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Tentativa'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('student', 'activity_link', 'attempt_number'), name='unique_student_activity_attempt'),
        ),
    ]
