# Generated by Django 6.0.3 on 2026-09-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='role',
            field=models.CharField(blank=True, choices=[('professor', 'Professor'), ('aluno', 'Aluno')], default='', max_length=10),
        ),
    ]
